"""Compile a generated project to PDF with latexmk (one-shot or watch mode).

Also handles a couple of quality-of-life features: locating the project's
main .tex file by convention, picking the right engine flag from the
project's VS Code settings, and (on TeX Live) auto-installing missing
packages reported in the compilation log and retrying once.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

_ENGINE_FLAGS = ("-lualatex", "-xelatex", "-pdf")
_DEFAULT_FLAG = "-lualatex"
_MISSING_FILE_PATTERN = re.compile(r"File `([^']+)' not found")


def _detect_latexmk_flag(project_dir: Path) -> str:
    """Read the engine flag from the project's .vscode/settings.json.

    Projects generated by latex-forge embed their latexmk invocation in the
    LaTeX Workshop tool definition; reuse it so `build` always matches what
    VS Code would do. Falls back to LuaLaTeX.
    """
    settings_path = project_dir / ".vscode" / "settings.json"
    try:
        data = json.loads(settings_path.read_text(encoding="utf-8"))
        tools = data.get("latex-workshop.latex.tools", [])
        for arg in tools[0].get("args", []):
            if arg in _ENGINE_FLAGS:
                return arg
    except (OSError, json.JSONDecodeError, IndexError, AttributeError, TypeError):
        pass
    return _DEFAULT_FLAG


def _find_main_tex(project_dir: Path) -> Path:
    """Resolve the main .tex file of a project.

    Prefers `<folder-name>.tex` (the latex-forge convention), accepts a single
    root .tex file otherwise.
    """
    by_name = project_dir / f"{project_dir.name}.tex"
    if by_name.exists():
        return by_name

    tex_files = sorted(p for p in project_dir.glob("*.tex") if p.is_file())
    if not tex_files:
        raise FileNotFoundError(
            f"No .tex file found in {project_dir}.\n"
            "Run this command from inside a latex-forge project, "
            "or pass the project directory as an argument."
        )
    if len(tex_files) == 1:
        return tex_files[0]
    names = ", ".join(p.name for p in tex_files)
    raise ValueError(
        f"Several .tex files found in {project_dir}: {names}\n"
        f"The main file must be named after the folder: {project_dir.name}.tex\n"
        "Tip: latex-forge rename <new-name> keeps them in sync."
    )


def build_command(
    project_dir: Path, watch: bool = False, verbose: bool = False
) -> list[str]:
    """Return the latexmk invocation for *project_dir* (used by run_build and tests)."""
    main_tex = _find_main_tex(project_dir)
    command = [
        "latexmk",
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        _detect_latexmk_flag(project_dir),
        "-outdir=build",
        main_tex.name,
    ]
    if not verbose:
        # Errors and warnings still come through; full logs live in build/*.log
        command.insert(1, "-quiet")
    if watch:
        command.insert(1, "-pvc")
    return command


def _find_missing_files(log_path: Path) -> list[str]:
    """Return the .sty/.cls file names latexmk reported as missing, from its log."""
    if not log_path.exists():
        return []
    text = log_path.read_text(encoding="utf-8", errors="replace")
    return sorted(set(_MISSING_FILE_PATTERN.findall(text)))


def _tlmgr_package_for_file(filename: str) -> str | None:
    """Find which TeX Live package provides *filename* via `tlmgr search`."""
    result = subprocess.run(
        ["tlmgr", "search", "--global", "--file", f"/{filename}"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    package = None
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip("\t "))
        if indent == 0:
            continue  # the searched-for file name itself
        if indent == 1:
            package = line.strip().rstrip(":")
        elif package:
            return package
    return None


def _install_missing_packages(missing_files: list[str]) -> list[str]:
    """Try to install the TeX Live packages providing *missing_files*.

    Returns the package names that were successfully installed. No-op (returns
    an empty list) if `tlmgr` is not on PATH, e.g. on MiKTeX where missing
    packages are installed automatically by the engine itself.
    """
    if shutil.which("tlmgr") is None:
        return []

    installed = []
    for filename in missing_files:
        package = _tlmgr_package_for_file(filename)
        if package is None:
            continue
        result = subprocess.run(
            ["tlmgr", "install", package],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            installed.append(package)
    return installed


def run_build(
    project_dir: Path | None = None,
    watch: bool = False,
    clean: bool = False,
    verbose: bool = False,
) -> int:
    """Compile the project once, or continuously when *watch* is True.

    Returns the latexmk exit code (0 on success).
    Raises FileNotFoundError/ValueError when the project layout is wrong.
    """
    directory = (project_dir or Path.cwd()).resolve()
    if not directory.is_dir():
        raise FileNotFoundError(f"Project directory not found: {directory}")

    if shutil.which("latexmk") is None:
        print("latexmk was not found on your PATH.")
        print("Install the LaTeX toolchain with: latex-forge setup --install-tex")
        return 1

    if clean:
        shutil.rmtree(directory / "build", ignore_errors=True)

    command = build_command(directory, watch=watch, verbose=verbose)
    main_name = command[-1]

    if watch:
        print(f"Watching {main_name} — press Ctrl+C to stop.", flush=True)
    else:
        print(f"Compiling {main_name} …", flush=True)

    try:
        result = subprocess.run(command, cwd=directory, check=False)
    except KeyboardInterrupt:
        print("\nStopped.")
        return 0

    if result.returncode != 0 and not watch:
        log_path = directory / "build" / f"{Path(main_name).stem}.log"
        missing_files = _find_missing_files(log_path)
        if missing_files:
            print(f"Missing package files: {', '.join(missing_files)}")
            print("Trying to install them with tlmgr …", flush=True)
            installed = _install_missing_packages(missing_files)
            if installed:
                print(f"Installed: {', '.join(installed)}. Recompiling …", flush=True)
                result = subprocess.run(command, cwd=directory, check=False)
            else:
                print("Could not auto-install (tlmgr unavailable, offline, or no match).")

    if result.returncode == 0 and not watch:
        pdf = directory / "build" / (Path(main_name).stem + ".pdf")
        print(f"PDF ready: {pdf}")
    elif result.returncode != 0:
        print("")
        print("Compilation failed. Common fixes:")
        print("  - Missing package  ->  tlmgr install <package>")
        print("  - Stale artifacts  ->  latex-forge build --clean")
        print("  - Check the log    ->  build/*.log")

    return result.returncode
